# Generated by Django 3.2.9 on 2021-12-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
